<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Canalizacion extends Model
{
    protected $fillable =[
        'raizal',
        'palenquero',
        'gitano',
        'indigena',
        'afrodescendiente',
        'ese',
        'eapb',
        'secretariaSalud',
        'sac',
        'siau',
        'ips',
        'saludOtro',
        'policia',
        'cti',
        'secretariaGobierno',
        'registraduria',
        'fiscalia',
        'inspeccionPolicia',
        'justiciaOtro',
        'icbf',
        'defensoriaPueblo',
        'personeria',
        'comisariaFamilia',
        'proteccionOtro',
        'institucionEducativa',
        'sena',
        'universidad',
        'alfabetizacion',
        'educacionOtro',
        'proyectosProductivos',
        'economiaOtro',
        'unidadVictimas',
        'familiasAccion',
        'jovenesAccion',
        'programaAdultoMayor',
        'inclucionOtro',
        'gruposApoyo',
        'organizacionConDiscapacidad',
        'casaCultura',
        'deportesRecreacion',
        'redUnidos',
        'socialOtro',
        'programa',
        'porquePrograma',
        'estrategia',
        'porqueEstrategia',
        'proyecto',
        'porqueProyecto',
        'servicio',
        'porqueServicio',
        'nombrePaciente',
        'tipoDocumento',
        'numeroIdentidad',
        'paciente_id',
    ];
}
