<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Seguimiento extends Model
{
    protected $fillable = [
        'nombreCompleto',
        'tipoDocumento',
        'documento',
        'direccion',
        'telefono',
        'nombreCuidador',
        'beneficiarioEnDireccion',
        'institucional',
        'comunitaria',
        'sitioDelBeneficiario',
        'cualBeneficiario',
        'nuevaDireccion',
        'nuevoMunicipio',
        'internadoIps',
        'tiempo',
        'canalizado2018',
        'logrosObtenidos',
        'servicioCanlizado',
        'porqueNoSolicitoServicio',
        'recivioElServicio',
        'razonNoServicio',
        'barreraEncontrada',
        'cualFueLaBarrera',
        'porqueNoRecibioServicio',
        'diagnostico',
        'estadoActualEnfermedad',
        'historiaClinica',
        'tomaMedicamentos',
        'cualMedicamentos',
        'horariosTomaMedicamentos',
        'actividadesParalelas',
        'cualActividades',
        'deberiaCapacitarse',
        'enQueCapacitar',
        'ocupacion',
        'hijos',
        'cantidadHijos',
        'dependienteIndependiente',
        'numeroPersonasEncargadas',
        'parentescoPersonasEncargadas',
        'deporte',
        'tipoDeporte',
        'reunionesFamiliares',
        'grupoRelijioso',
        'tipoGrupoRelijioso',
        'voluntariadoOGrupoComunidad',
        'tipoDeGrupoVoluntariado',
        'grupoAutoayuda',
        'tipoDeGrupoAutoayuda',
        'organizacionCondiscapacidad',
        'tipoOrganizacionConDiscapacidad',
        'participacionPolitica',
        'tipoParticipacionPolitica',
    ];
}
